version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - laravel
    networks:
      - app-network

  laravel:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel
    working_dir: /var/www/html
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    expose:
      - "9000"
    depends_on:
      - postgres
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: worker
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - REDIS_HOST=${REDIS_HOST}
    entrypoint: []
    command: php artisan horizon
    healthcheck:
        test: [ "CMD", "php", "artisan", "horizon:status" ]
        interval: 30s
        timeout: 10s
        retries: 3
    depends_on:
      - laravel
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app-network

  postgres:
    image: postgres:18.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - notif_postgres:/var/lib/postgresql
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
        - postgres
    ports:
        - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis:
    driver: local
  notif_postgres:
    driver: local
